#-------------------------------------------------------------------------------
# Note for using the rate-limiting:
#   The comment part won't be copied if you use the subgenerator docker-compose
#   you have to manually copy it
#-------------------------------------------------------------------------------
version: '2'
services:
    springgateway-app:
        image: springgateway
        external_links:
            - springgateway-mysql:mysql
            # Uncomment to have Cassandra working with the gateway
            # - springgateway-cassandra:cassandra
            - springgateway-elasticsearch:elasticsearch
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/springgateway?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8010:8010
    springgateway-mysql:
        extends:
            file: mysql.yml
            service: springgateway-mysql
    # Uncomment to have Cassandra working with the gateway
    # springgateway-cassandra:
    #     extends:
    #         file: cassandra-cluster.yml
    #         service: springgateway-cassandra
    # springgateway-cassandra-migration:
    #     extends:
    #         file: cassandra-migration.yml
    #         service: springgateway-cassandra-migration
    #     environment:
    #         - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
    springgateway-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: springgateway-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
